#激活哪一个环境的配置文件
spring:
  profiles:
    active: dev 

---
# 配置端口
server:
  port: 8092
  servlet:
    context-path: /service-life

spring:
  profiles: dev
  application:
    name: service-life
  # 配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.52.216.164:3306/life?useUnicode=true&characterEncoding=utf-8
    username: life
    password: life123
    filters: stat
  main:
    allow-bean-definition-overriding: true

###服务注册到eureka地址
eureka:
  instance:
    prefer-ip-address: true
    #每隔5秒就发送一次心跳
    lease-renewal-interval-in-seconds: 5
    #10秒钟不发送就过期
    lease-expiration-duration-in-seconds: 10
  client:
    enabled: true
    serviceUrl:
      #dev环境
      #defaultZone: http://106.52.216.164:8761//eureka
      defaultZone: http://172.16.0.11:8761/eureka

#请求处理的超时时间
ribbon:
  ReadTimeout: 600000
  ConnectTimeout: 600000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false

# ====================MybatisPlus====================
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:com/own/life/modular/**/mapper/mappering/**.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.own.life.modular.*.entity
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      #id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      #field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
      #驼峰下划线转换
      column-underline: false
      #数据库大写下划线转换
      #      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
    refresh: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl